version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/qcmnagai/esampo
    steps:
      - checkout
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run: go build -o ./bin/esampo
      - save_cache:
          key: v1-pkg-cache
          paths:
            - bin
            - vendor
  release:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/qcmnagai/esampo
    steps:
      - checkout
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run: gox --osarch "windows/386 windows/amd64" --output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
      - run: ghr -t $GITHUB_TOKEN -u $USERNAME -r $CIRCLE_PROJECT_REPONAME v$(./bin/esampo --version | cut -d " " -f 3) dist/
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
